---
# Playbook para demo Ansible
#

# Play para provisionar una m치quina con la paqueteria necesaria
- name: Play para la provisi칩n de m치quinas.
  hosts: devops0.local
  user: vagrant
  become: true
  vars:
    lista_paquetes:
      - httpd
      - java

  tasks:
    - name: Instala paquetes en m치quina a gestionar.
      yum:
        name: "{{ lista_paquetes }}"
        state: latest

    - name: Comprueba que los paquetes se hayan instalado
      shell: yum list installed | grep {{ item }}
      with_items: "{{ lista_paquetes }}"
      register: paquetes_instalados

    - name: Muestra estado de los paquetes
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ paquetes_instalados.results }}"
...
