---
# Playbook para demo Ansible
#
#

# Play para los usuarios de una m치quina.
- name: Play para la gesti칩n de usuarios.
  hosts: devops0.local
  user: vagrant
  become: true
  vars:
    lista_usuarios:
      - userdevops1
      - userdevops2
      - userdevops3

  tasks:
    - name: A침ade usuarios a la m치quina
      user:
        name: "{{ item }}"
        state: present
      with_items: "{{ lista_usuarios }}"

    - name: Borra un usuario de la lista
      user:
        name: "{{ lista_usuarios[2] }}"
        state: absent

    - name: Comprueba los usuarios existentes en el sistema
      shell: getent passwd | grep {{ item }}
      with_items: "{{ lista_usuarios }}"
      ignore_errors: yes

...