---
# Playbook para instalar Sonarqube 
# SonarQube
#

# Play para Configurar la m치quina, instalar Apache y Sonarqube
- name: Instalacion SonarQube
  hosts: devops2.local
  user: vagrant
  become: true
  roles:
    - { role: "host_config"}
    - { role: "apache2" }
    - { role: "sonarqube" }

# Play para Validar la instalaci칩n de Sonarqube
- name: Validaci칩n de la instalaci칩n de Sonarqube
  hosts: devops2.local
  user: vagrant
  become: true
  roles:
    - { role: "test_deploy" }

...
