---
galaxy_info:
  author: Devops Xeridia
  description: CentOS 7 Full or Security Updates
  min_ansible_version: 2.4
  license: GPLv3
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
  - system

dependencies: []
...
